# App config
spring.application.name=porbe
server.port=8080

# Database configuration
spring.datasource.url=jdbc:sqlite:stocktracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.generate-ddl=true
# Export schema script to a file
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.script.append=false
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/schema.sql
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.tool.hbm2ddl=DEBUG

spring.devtools.restart.enabled = false

# Scheduling configuration (for daily stock queries)
stock.scheduler.cron.daily=0 0 17 * * MON-FRI

# Weekly report configuration (Friday 6pm EST/GMT-5)
report.scheduler.cron.weekly=0 0 18 * * FRI

