create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(255) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table portfolio (
    id bigint generated by default as identity primary key,
    user_id bigint references app_user(id),
    name varchar(120) not null,
    base_currency char(3) not null default 'COP',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create index idx_portfolio_user on portfolio(user_id);
