create table import_batch (
    id bigint generated by default as identity primary key,
    portfolio_id bigint not null references portfolio(id),
    source_filename varchar(255) not null,
    file_hash varchar(64) not null unique,
    row_count integer not null,
    imported_by varchar(100) not null,
    imported_at timestamp with time zone not null default current_timestamp
);

create table portfolio_operation (
    id bigint generated by default as identity primary key,
    portfolio_id bigint not null references portfolio(id),
    import_batch_id bigint not null references import_batch(id),
    operation_date date not null,
    operation_type varchar(20) not null,
    ticker varchar(30),
    asset_name varchar(160),
    quantity numeric(24, 8),
    unit_price numeric(24, 8),
    commission numeric(24, 2) not null default 0,
    total_amount numeric(24, 2) not null,
    notes varchar(1000),
    created_at timestamp with time zone not null default current_timestamp,
    constraint chk_portfolio_operation_type check (
        operation_type in ('COMPRA', 'VENTA', 'DIVIDENDO', 'DEPOSITO', 'RETIRO')
    ),
    constraint chk_portfolio_operation_commission check (commission >= 0),
    constraint chk_portfolio_operation_total check (total_amount > 0)
);

create index idx_import_batch_portfolio on import_batch(portfolio_id, imported_at desc);
create index idx_portfolio_operation_portfolio_date
    on portfolio_operation(portfolio_id, operation_date desc, id desc);
create index idx_portfolio_operation_ticker_date
    on portfolio_operation(ticker, operation_date desc);
