CREATE TABLE market_instrument (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(160),
    currency VARCHAR(3),
    exchange_code VARCHAR(30),
    instrument_type VARCHAR(30),
    exchange_timezone VARCHAR(80),
    last_synced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE market_price_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT NOT NULL REFERENCES market_instrument(id),
    price_date DATE NOT NULL,
    open_price NUMERIC(24, 8),
    high_price NUMERIC(24, 8),
    low_price NUMERIC(24, 8),
    close_price NUMERIC(24, 8) NOT NULL,
    adjusted_close NUMERIC(24, 8),
    volume BIGINT,
    final_close BOOLEAN NOT NULL DEFAULT FALSE,
    source VARCHAR(30) NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_market_price_daily_instrument_date UNIQUE (instrument_id, price_date),
    CONSTRAINT chk_market_price_daily_prices CHECK (
        close_price >= 0
        AND (open_price IS NULL OR open_price >= 0)
        AND (high_price IS NULL OR high_price >= 0)
        AND (low_price IS NULL OR low_price >= 0)
        AND (adjusted_close IS NULL OR adjusted_close >= 0)
    ),
    CONSTRAINT chk_market_price_daily_volume CHECK (volume IS NULL OR volume >= 0)
);

CREATE INDEX idx_market_price_daily_instrument_date
    ON market_price_daily(instrument_id, price_date DESC);
