alter table import_batch
    add column source_type varchar(20) not null default 'IMPORT';

alter table import_batch
    add constraint chk_import_batch_source_type
        check (source_type in ('IMPORT', 'MANUAL'));

alter table portfolio_operation
    add column updated_at timestamp with time zone not null default current_timestamp;

alter table portfolio_operation
    add column updated_by varchar(100) not null default 'sistema';

update portfolio_operation operation
set updated_by = (
    select batch.imported_by
    from import_batch batch
    where batch.id = operation.import_batch_id
);

create table operation_audit (
    id bigint generated by default as identity primary key,
    operation_id bigint,
    import_batch_id bigint,
    action varchar(30) not null,
    username varchar(100) not null,
    details varchar(500) not null,
    previous_data text,
    new_data text,
    created_at timestamp with time zone not null default current_timestamp,
    constraint chk_operation_audit_action check (
        action in ('CREATED', 'UPDATED', 'DELETED', 'BATCH_REVERTED')
    )
);

create index idx_operation_audit_created_at on operation_audit(created_at desc);
