ALTER TABLE market_instrument
    ADD COLUMN sector VARCHAR(80);

CREATE TABLE market_data_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_key VARCHAR(40) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    day_of_week VARCHAR(9) NOT NULL,
    run_time TIME NOT NULL,
    timezone VARCHAR(80) NOT NULL,
    last_run_at TIMESTAMP WITH TIME ZONE,
    last_run_status VARCHAR(20),
    last_run_message VARCHAR(500),
    updated_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_market_schedule_day CHECK (
        day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

INSERT INTO market_data_schedule (
    schedule_key,
    enabled,
    day_of_week,
    run_time,
    timezone,
    updated_by
) VALUES (
    'PORTFOLIO_CLOSES',
    FALSE,
    'SATURDAY',
    '08:00:00',
    'America/Bogota',
    'system'
);
