CREATE TABLE portfolio_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_from DATE NOT NULL,
    report_to DATE NOT NULL,
    baseline_date DATE NOT NULL,
    valuation_date DATE NOT NULL,
    base_currency VARCHAR(3) NOT NULL,
    trigger_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    generated_by VARCHAR(120) NOT NULL,
    valuation_complete BOOLEAN NOT NULL,
    provisional_prices INTEGER NOT NULL DEFAULT 0,
    image_data BYTEA,
    pdf_data BYTEA,
    image_size INTEGER NOT NULL DEFAULT 0,
    pdf_size INTEGER NOT NULL DEFAULT 0,
    delivery_status VARCHAR(30) NOT NULL DEFAULT 'NOT_CONFIGURED',
    delivery_message VARCHAR(500),
    error_message VARCHAR(1000),
    generated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_portfolio_report_dates CHECK (report_from <= report_to),
    CONSTRAINT chk_portfolio_report_trigger CHECK (trigger_type IN ('MANUAL', 'SCHEDULED')),
    CONSTRAINT chk_portfolio_report_status CHECK (status IN ('GENERATING', 'READY', 'FAILED')),
    CONSTRAINT chk_portfolio_report_delivery CHECK (
        delivery_status IN ('NOT_CONFIGURED', 'PENDING', 'SENT', 'FAILED')
    )
);

CREATE INDEX idx_portfolio_report_created_at ON portfolio_report(created_at DESC);
CREATE INDEX idx_portfolio_report_period ON portfolio_report(report_from, report_to, trigger_type);
