# App config
spring.application.name=porbe
server.port=8080

# Database configuration
spring.datasource.url=jdbc:sqlite:stocktracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Scheduling configuration (for daily stock queries)
stock.scheduler.cron.daily=0 0 16 * * MON-FRI

# Weekly report configuration (Friday 6pm EST/GMT-5)
report.scheduler.cron.weekly=0 0 18 * * FRI

